Repository promised-ai/lace, pull requests merged in 2023-09, with the labels that each got.

#125 WIP: Expose component parameters in pylace
  pylace/Cargo.lock
  pylace/lace/engine.py
  pylace/src/component.rs
  pylace/src/lib.rs
Labels: enhancement, Python

#127 Feat/copyable pylace engine
  CHANGELOG.md
  pylace/src/lib.rs
  pylace/src/utils.rs
  pylace/tests/test_engine.py
Labels: enhancement, Python

#126 fix: Fixed a few pylace bugs
  CHANGELOG.md
  pylace/lace/codebook.py
  pylace/src/lib.rs
  pylace/src/utils.rs
  pylace/tests/test_index_names.py
Labels: bug, Python

#134 Docs/2023 09 28 updates and fixes
  README.md
  assets/animals-convergence.png
  assets/animals-depprob.png
  assets/sats-depprob.png
  assets/sats-period-uncertainty.png
  book/src/appendix/references.md
  book/src/appendix/stats-primer.md
  book/src/assets/animals-convergence.png
  book/src/assets/animals-depprob.png
  book/src/workflow/workflow.md
  book/theme/index.hbs
Labels: documentation
